### ISSUE TITLE
要怎么写才能在ｔｏｋｅｎ错误或者没有ｔｏｋｅｎ的时候，返回一个ｊｓｏｎ

### ISSUE THREAD

**Issue by buzai** [okoala/egg-jwt#10]
要怎么写才能在ｔｏｋｅｎ错误或者没有ｔｏｋｅｎ的时候，返回一个ｊｓｏｎ

{
   code:1,
   success:false,
   message:'token error'
}

**Comment by okoala** [comment]
可以自己写一个中间件进行拦截处理

**Comment by buzai** [comment]
@okoala 您的意思是我先写一个中间件，需要进行ｔｏｋｅｎ验证的接口首先被我的中间件处理，检测是否有ｔｏｋｅｎ在ｈｅａｄｅｒｓ里是吗？
