### ISSUE TITLE
通过匹配路由好像不起作用？

### ISSUE THREAD

**Issue by LuHugo** [okoala/egg-jwt#15]
在项目中添加了egg-jwt，配置了match匹配 /api/启用jwt，但是还是所有的路由都进行了身份校验。
eggjs版本2.x

配置：
config.jwt = {
    secret: 'tttttt',
    enable: true,
    macth: '/api/',
  };

路由：
  router.get('/', controller.home.index);
  /**
   * rest api
   */
  router.post('/api/user/signin', controller.api.user.signin);
  router.post('/api/user/signup', controller.api.user.signup);

**Comment by LuHugo** [comment]
犯了低级错误，match单词写错了

**Comment by shen-lan** [comment]
请问下  verify具体是如何处理的？

**Comment by okoala** [comment]
@shen-lan 
https://github.com/okoala/koa-jwt2/blob/master/lib/index.js#L115
