### ISSUE TITLE
app.jwt 不可像 koa-jwt2 一样进行参数配置 

### ISSUE THREAD

**Issue by sfyr111** [okoala/egg-jwt#19]
koa-jwt2 可以使用 ge('/', jwt(options), fn) 进行注销、未注册用户访问配置
egg-jwt 只能 ge('/', app.jwt, fn) , 使用 app.jwt(options) 出现报错

```
Error: get `/articles/:slug`: `middleware` must be a function, not `object`
```

**Comment by okoala** [comment]
app.middlewares.jwt 可以拿到中间件

例子：
https://github.com/okoala/egg-jwt/blob/master/test/fixtures/apps/jwt-router-middleware/app/router.js
