### ISSUE TITLE
使用 verify 和 sign 方法时，为什么不自动读取已有的配置呢？

### ISSUE THREAD

**Issue by seekcx** [okoala/egg-jwt#23]
如题，看了相关代码 https://github.com/okoala/egg-jwt/blob/master/app/extend/application.js#L12-L14 只是简单挂载了一下 jsonwebtoken 的方法。

**Comment by seekcx** [comment]
除了实现读取已有配置外，应该还用 promise 包装一下。

**Comment by okoala** [comment]
谢谢反馈，PR 有些问题，你看看~
