### ISSUE TITLE
在Mac系统与Linux系统上调用jwt.sign()方法时报错

### ISSUE THREAD

**Issue by williamnie** [okoala/egg-jwt#25]
您好，我在使用egg-jwt时遇到了一个问题，在调用sign方法时，遇到了报错，根据提示我找到了sign.js 文件，并在里面发现了一些问题，特地来请教下。
我的config配置如下：
`
  config.jwt = {
    secret: 'Great4-M',
    enable: true, // default is false
    match: '/jwt', // optional
  };
`
调用方法如下：
`
async apply(_id) {
    const {ctx} = this;
    return ctx.app.jwt.sign({
      data: {
        _id: _id
      },
      exp: Math.floor(Date.now() / 1000) + (60 * 60 * 24 * 7)
    }, ctx.app.config.jwt.secret);
  }
`
问题如下：
`module.exports = function (payload, secretOrPrivateKey, options, callback) {
   console.log('payload',payload)
  console.log('secretOrPrivateKey',secretOrPrivateKey)
  console.log('options',options)
    console.log('callback',callback)
`
在Mac系统上执行这段代码时，打印的结果是
`
payload { data: { _id: 5b67b41d6b251132fa770c81 }, exp: 1534148604 }
secretOrPrivateKey Great4-M
options undefined
callback undefined
`
而在Linux系统上打印时，缺变成了这样
`
payload { data: { name: '4444444' }, exp: 1534148370 }
secretOrPrivateKey Great4-M
options { '0': 'G',
  '1': 'r',
  '2': 'e',
  '3': 'a',
  '4': 't',
  '5': '4',
  '6': '-',
  '7': 'M' }
callback undefined
`
观察发现，在Mac系统上时，secretOrPrivateKey 这个属性是调用sign方法时传入的，但是到了线上的linux系统时，就变成了从config里面自己读取的了，这样就会重复的出现，而options的位置就会被占用，从而报错。
不知道是我的用法不对，还是包有些问题，请您查看，希望能得到指导

**Comment by williamnie** [comment]
刚刚看了您的commit，发现已经是自己读取了，我的问题也解决了，建议您更改下remandme里面的用法

**Comment by okoala** [comment]
@williamnie 不好意思，上一个版本有问题~
