### ISSUE TITLE
egg-jwt 的正确使用姿势

### ISSUE THREAD

**Issue by littledu** [okoala/egg-jwt#26]
我理想的操作步骤：

1. 配置config
2. `plugin.js` 开启插件
3. `router.js` 里面针对哪个 url 想鉴权就加上 middleware

但我发现这样做了没用，访问的时候直接告诉我没有权限，然后我需要这么做：

1. 登录接口调用 `sign` 生成 token, 返回给客户端(cookie或者客户端自行保存到localstore)
2. 鉴权的请求收到时，调用 `verify` 进行解码 token, 然后进行验证

没能怎么搜到相关 demo， 不知道我的使用方式对不对。

**Comment by okoala** [comment]
例子在 test/fixtures/apps 中

**Comment by littledu** [comment]
@okoala 谢谢，看了下，我的理解应该是对的

**Comment by shen-lan** [comment]
> @okoala 谢谢，看了下，我的理解应该是对的
demo中没看到如何进行verify 的，求教
