### ISSUE TITLE
为什么用异步的方法 不回调

### ISSUE THREAD

**Issue by kuhippo** [okoala/egg-jwt#29]
app.jwt.verify(ctx.request.header.authorization, app.config.jwt.secret, function(err, decoded) {
      console.log('1');
    });
为什么用异步的方法 不回调

**Comment by okoala** [comment]
你先调试下？

**Comment by d0apga** [comment]
问题出在这里，传递的function转换成了object
[https://github.com/okoala/egg-jwt/blob/7b35915ef2a0be001b1c980beb701762bf5b3c98/app/extend/application.js#L36](url)

**Comment by okoala** [comment]
已修复
egg-jwt@3.1.2
