### ISSUE TITLE
jwt.sign 传入参数无效

### ISSUE THREAD

**Issue by xluos** [okoala/egg-jwt#41]
如图
当我传入过期时间时，得不到预期的结果

![image](https://user-images.githubusercontent.com/23625189/54210895-5096bb80-451b-11e9-9b22-873acce15f05.png)

而我直接使用jsonwebtoken库时时得到的结果与预期的一致。

![image](https://user-images.githubusercontent.com/23625189/54210944-64dab880-451b-11e9-82b1-d170d2369bdd.png)

猜测原因：因为看到之前有一个建议使用内部配置的Issues，已经mr进来了。可能是使用默认配置时将传入的配置覆盖了，导致传入失效。

**Comment by okoala** [comment]
意思是漏了一个过期时间的配置是吧？

**Comment by xluos** [comment]
> 意思是漏了一个过期时间的配置是吧？

感觉像是[这一行的原因](https://github.com/okoala/egg-jwt/blob/4579a1756f1f07980fc400df52f476448ca56977/app/extend/application.js#L27)，因为我第二个参数传入对象时（也就是使用默认配置[执行这个if逻辑的时候是正常的](https://github.com/okoala/egg-jwt/blob/4579a1756f1f07980fc400df52f476448ca56977/app/extend/application.js#L15)）过期时间是有效的。但是我不知道要怎么调试插件，麻烦帮忙看一下。

**Comment by okoala** [comment]
@xluos 我这边无法重现，你用 ctx.app.jwt.sign 和 ctx.app.jwt.decode 看看

**Comment by shen-lan** [comment]
楼主的vscode 哪个主题？

**Comment by xluos** [comment]
> 楼主的vscode 哪个主题？

Chester Atom

**Comment by shen-lan** [comment]
> > 楼主的vscode 哪个主题？
> 
> Chester Atom
效果好像不太一样。貌似是用了括号成对匹配的扩展？

**Comment by fairyly** [comment]
如果配置没问题的话，使用  
```
this.app.jwt
````
