### ISSUE TITLE
index.d.ts里的EggAppConfig定义里没有match和ignore

### ISSUE THREAD

**Issue by jijijijidaipi** [okoala/egg-jwt#46]
interface EggAppConfig {
    jwt: {
      secret: string;
      enable?: boolean;
      sign?: SignOptions;
      verify?: VerifyOptions;
    };
  }

**Comment by hzgotb** [comment]
#47 已修复

**Comment by Magin-CC** [comment]
> #47 已修复

为啥不更到npm上啊老哥

**Comment by hzgotb** [comment]
> > #47 已修复
> 
> 为啥不更到npm上啊老哥

@okoala 老哥更一下。

**Comment by okoala** [comment]
https://github.com/okoala/egg-jwt/pull/47
有问题，你这  PR 不纯粹啊~ 应该只提交 index.d.ts 就可以了~

**Comment by hzgotb** [comment]
> #47
> 有问题，你这 PR 不纯粹啊~ 应该只提交 index.d.ts 就可以了~

#50

**Comment by okoala** [comment]
egg-jwt@3.1.7
