### ISSUE TITLE
mw is not a function

### ISSUE THREAD

**Issue by barretzhi** [okoala/egg-jwt#8]
不知道为啥出现mw is not a function？

**Comment by okoala** [comment]
@barretzhi  请给更加信息的日志信息

**Comment by barretzhi** [comment]
@okoala 找到问题了，但是问个问题error msg 怎么自定义呢{"error":"No authentication token found\n"}？是自己重新添加middleware 中自定义吗

**Comment by okoala** [comment]
@barretzhi  需要自己写中间件处理下 https://eggjs.org/zh-cn/basics/middleware.html

**Comment by alabihula** [comment]
@barretzhi 能问下这个问题你怎么解决的么 我也遇到了就是 简单的编写了一个中间件启动就报错了
