### ISSUE TITLE
返回类型怎么设置为json

### ISSUE THREAD

**Issue by kunzhijia** [okoala/egg-jwt#9]
现在返回的类型是html，请问怎么设置，
验证失败时，我在我的middleware中无法捕获到error，只能在app.on(error,callback)中才能捕获，但是此时好像拿不到ctx

**Comment by kunzhijia** [comment]
这个已经解决，需要在自己的app.js配置我的中间件，将我的中间件放在jwt中间件前面即可解决。

```
// app.js
module.exports = app => {
  // 在中间件最前面统计拦截所有错误
  app.config.coreMiddleware.unshift('errorHandler');
};
```

**Comment by buzai** [comment]
@kunzhijia 
要怎么写才能在ｔｏｋｅｎ错误或者没有ｔｏｋｅｎ的时候，返回一个ｊｓｏｎ
```
{
   code:1,
   success:false,
   message:'token error'
}
```
